name       : bibtool
version    : 2.67
release    : 1
source     :
    - https://github.com/ge-ne/bibtool/releases/download/BibTool_2_67/BibTool-2.67.tar.gz : 5b6c4160975a926356e8e59d0e5c01ac2a7be337ecace2494918fc2a46d9d784
license    : GPL-2.0
component  : editor
summary    : A tool for manipulating BibTeX databases
description: |
    BibTeX provides an easy to use means to integrate citations and
    bibliographies into LaTeX documents. But the user is left alone with
    the management of the BibTeX files.
    The program BibTool is intended to fill this gap. BibTool allows the
    manipulation of BibTeX files which goes beyond the possibilities and
    intentions of BibTeX.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALL_DIR="install -dm644" INSTALLPREFIX=$installdir

